/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cafe;

import javax.swing.JOptionPane;

/**
 *
 * @author nural
 */
public class homeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form homeAdmin
     */
    public homeAdmin(String username) {
        initComponents();
        lUsername.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMyCafe = new javax.swing.JToggleButton();
        btnTransaction = new javax.swing.JToggleButton();
        btnAbout = new javax.swing.JToggleButton();
        btnCredits = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JToggleButton();
        lUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMyCafe.setBackground(new java.awt.Color(255, 153, 0));
        btnMyCafe.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnMyCafe.setForeground(new java.awt.Color(255, 255, 255));
        btnMyCafe.setText("MY CAFE");
        btnMyCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCafeActionPerformed(evt);
            }
        });
        jPanel2.add(btnMyCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 27, 160, 39));

        btnTransaction.setBackground(new java.awt.Color(255, 153, 0));
        btnTransaction.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        btnTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaction.setText("TRANSACTION");
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 94, 160, 39));

        btnAbout.setBackground(new java.awt.Color(255, 153, 0));
        btnAbout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("ABOUT");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 161, 160, 39));

        btnCredits.setBackground(new java.awt.Color(255, 153, 0));
        btnCredits.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnCredits.setForeground(new java.awt.Color(255, 255, 255));
        btnCredits.setText("CREDITS");
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });
        jPanel2.add(btnCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 227, 160, 39));

        btnExit.setBackground(new java.awt.Color(255, 153, 0));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 293, 160, 39));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 230, 360));

        lUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lUsername.setForeground(new java.awt.Color(255, 255, 255));
        lUsername.setText("Hi,");
        jPanel1.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hi,");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMyCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCafeActionPerformed
        // TODO add your handling code here:
        new detailMenu(lUsername.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyCafeActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:'
        new aboutAdmin(lUsername.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(null, "Do You Want To Exit?","EXIT", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
          System.exit(0);
        }
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
        // TODO add your handling code here:
        new creditsAdmin(lUsername.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreditsActionPerformed

    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
        // TODO add your handling code here:
        new transaction(lUsername.getText()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeAdmin("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAbout;
    private javax.swing.JToggleButton btnCredits;
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnMyCafe;
    private javax.swing.JToggleButton btnTransaction;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lUsername;
    // End of variables declaration//GEN-END:variables
}
